[tools]
go = "latest"
golangci-lint = "latest"
gotestsum = "latest"

[vars]
PKGVERSION = '{{exec(command="git describe --tags --abbrev=8 --dirty --always --long")}}'
LDFLAGS = "{{ get_env(name='LDFLAGS',default='-w -s') }} -X 'main.Version={{vars.PKGVERSION}}'"

[tasks.build]
depends = ["build-amd64", "build-arm64"]


[tasks.build-amd64]
depends = ["generate"]
description = "Build the project for amd64"
sources = ["go.mod", "go.sum", "go.work", "go.work.sum", "**/*.go"]
outputs = ["./bin/athanor-amd64"]
env = { GOOS = "linux", GOARCH = "amd64", CGO_ENABLED = 0 }
run = 'go build -ldflags="{{vars.LDFLAGS}}" -o bin/athanor-amd64 ./cmd'

[tasks.build-arm64]
depends = ["generate"]
description = "Build the project for arm64"
sources = ["go.mod", "go.sum", "go.work", "go.work.sum", "**/*.go"]
outputs = ["./bin/athanor-amd64"]
env = { GOOS = "linux", GOARCH = "arm64", CGO_ENABLED = 0 }
run = 'go build -ldflags="{{vars.LDFLAGS}}" -o bin/athanor-arm64 ./cmd'

[tasks.check]
depends = ["lint", "test"]
description = "Run linters and tests"

[tasks.generate]
description = "Run go:generate"
sources = ["go.mod", "go.sum", "go.work", "go.work.sum", "**/*.go"]
run = "go generate ./..."

[tasks.lint]
wait_for = ["test"]
description = "Run linters"
hide = true
sources = ["go.mod", "go.sum", "go.work", "go.work.sum", "**/*.go"]
run = "golangci-lint run"

[tasks.test]
description = "Run tests"
sources = ["go.mod", "go.sum", "go.work", "go.work.sum", "**/*.go"]
run = "gotestsum ./..."

[tasks.install]
depends = ["build"]
run = "cp ./bin/athanor-amd64 ~/.local/bin/"

[tasks.ci]
env = { CGO_ENABLE = 0 }
depends = ["build", "check"]
usage = '''
arg <registry> help="Registry to push to"
arg <tag> help="Container tag to use"
'''
run = "docker buildx build -f Containerfile --platform linux/arm64,linux/amd64 --push -t {{usage.registry}}/athanor:{{usage.tag}} ."

[tasks.ci-release]
env = { CGO_ENABLE = 0 }
tools.gh = "latest"
depends = ["build", "check"]
usage = '''
arg <registry> help="Registry to push to"
arg <tag> help="Container tag to use"
'''
run = [
  "git remote add mirror git@github.com:stryan/athanor",
  "docker buildx build -f Containerfile --platform linux/arm64,linux/amd64 -t {{usage.registry}}/athanor:{{usage.tag}} -t {{usage.registry}}/athanor:stable -t ghcr.io/stryan/athanor:{{usage.tag}} -t ghcr.io/stryan/athanor:stable --push .",
  "gh release create {{usage.tag}} -d -F CHANGELOG.md --generate-notes ./bin/athanor*",
  "git remote rm mirror",
]

[tasks.container]
usage = '''
arg <tag> help="Container tag to use" default="latest"
'''
run = "podman build -f Containerfile.ci --platform=linux/amd64 -t primamateria.systems/athanor:{{usage.tag}} ."
